require: rubocop-rspec
Metrics/LineLength:
  Max: 120
AllCops:
  Exclude:
    - 'bin/*'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
