require: rubocop-rspec
Metrics/LineLength:
  Max: 120
AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/**/*'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ClassLength:
  Max: 110
RSpec/DescribeClass:
  Enabled: false
Style/Next:
  Enabled: false
Style/Lambda:
  Enabled: false
