development:
  sessions:
    default:
      database: workspace_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: workspace_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: wonkoweb_production
      hosts:
        - mongodb:27017
      options:
        max_retries: 1
        retry_interval: 0
